//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Practical_Exercise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int Id { get; set; }
        public string FirmName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int CarYear { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }
        public int Tickets { get; set; }
        public int Dui { get; set; }
        public string Coverage { get; set; }
        public decimal Quote { get; set; }
    }
}
